services:
  traefik:
    image: traefik:v2.3
    container_name: traefik
    env_file:
      - ${DOCKER_ENV_FILE?Variable not set}
    ports:
      - "80:80"
      - "443:443"
    restart: always
    labels:
      - traefik.enable=true
      - traefik.docker.network=jaunzenet-traefik
      - traefik.http.routers.traefik-dashboard.rule=Host(`${TRAEFIK_HOST_URL?Variable not set}`)
      - traefik.http.routers.traefik-dashboard.entrypoints=${TRAEFIK_ENTRYPOINTS?Variable not set}
      - traefik.http.routers.traefik-dashboard.tls=${TRAEFIK_TLS?Variable not set}
      - traefik.http.routers.traefik-dashboard.tls.certresolver=le
      - traefik.http.routers.traefik-dashboard.service=api@internal
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
      - traefik.http.routers.traefik-dashboard-http.middlewares=https-redirect
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - jaunzenet-traefik-certificates:/certificates
    command:
      - --api.dashboard=true
      - --api.insecure=false
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --log.level=${TRAEFIK_LOG_LEVEL:-INFO}
      - --certificatesresolvers.le.acme.email=${TRAEFIK_LE_EMAIL?Variable not set}
      - --certificatesresolvers.le.acme.storage=/certificates/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --accesslog
      - --log
      - --api
    networks:
      - jaunzenet-traefik

volumes:
  jaunzenet-traefik-certificates:

networks:
  jaunzenet-traefik:
    external: true
