services:
  postgresql:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${APL_GOLF_LEAGUE_API_DATABASE_USER?Variable not set}
      - POSTGRES_PASSWORD=${APL_GOLF_LEAGUE_API_DATABASE_PASSWORD?Variable not set}
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '${APL_GOLF_LEAGUE_API_DATABASE_PORT_EXTERNAL?Variable not set}:${APL_GOLF_LEAGUE_API_DATABASE_PORT_INTERNAL?Variable not set}'
    volumes:
      - ./database/postgresql/data:/var/lib/postgresql/data
      # copy scripts to create/fill tables (if not already initialized)
      - ./database/postgresql/aplgldb_backup_schema.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./database/postgresql/aplgldb_backup_data.sql:/docker-entrypoint-initdb.d/fill_tables.sql
    networks:
      - jaunzenet-postgresql

networks:
  jaunzenet-postgresql:
    external: false
