version: '3.7'
services:
    postgresql:
        image: postgres:latest
        restart: always
        environment:
          - POSTGRES_USER=${POSTGRES_USER?Environment variable not set}
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Environment variable not set}
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5432:5432'
        volumes: 
          - ./database/postgresql/data:/var/lib/postgresql/data
          # copy scripts to create/fill tables (if not already initialized)
          - ./database/postgresql/aplgldb-create-tables.20221201.sql:/docker-entrypoint-initdb.d/create_tables.sql
          - ./database/postgresql/aplgldb-fill-tables.20221201.sql:/docker-entrypoint-initdb.d/fill_tables.sql
