services:
  mongodb:
    image: mongo:latest
    volumes:
      - ./database/mongodb/init/:/docker-entrypoint-initdb.d
      - ./database/mongodb/init:/home/mongodb
      - ./database/mongodb/seed/:/home/mongodb/seed
      - test_mongo_data:/data/db
    ports:
      - "28000:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=TestRootUser
      - MONGO_INITDB_ROOT_PASSWORD=TestRootPassword
      - APP_USER=TestAppUser
      - APP_PWD=TestAppPassword
      - DB_NAME=TestDB
      - DB_COLLECTION_NAME=TestCollection
      - MONGO_HOSTNAME=mongodb

volumes:
  test_mongo_data: