"""initial schema

Revision ID: 499f7f88cfe5
Revises:
Create Date: 2026-02-01 23:06:11.249342

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "499f7f88cfe5"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "course",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("address", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("website", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "golfer",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "affiliation",
            sa.Enum(
                "APL_EMPLOYEE",
                "APL_RETIREE",
                "APL_FAMILY",
                "NON_APL_EMPLOYEE",
                name="golfer_affiliation_enum",
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("handicap_index", sa.Float(), nullable=True),
        sa.Column("handicap_index_updated", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "leaguedues",
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "FLIGHT_DUES",
                "TOURNAMENT_ONLY_DUES",
                name="league_dues_type_enum",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "officer",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column(
            "committee",
            sa.Enum(
                "LEAGUE",
                "EXECUTIVE",
                "RULES",
                "TOURNAMENT",
                "BANQUET_AND_AWARDS",
                "PUBLICITY",
                "PLANNING",
                name="committee_enum",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "season",
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("year"),
    )
    op.create_table(
        "team",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("disabled", sa.Boolean(), nullable=True),
        sa.Column("is_admin", sa.Boolean(), nullable=True),
        sa.Column("edit_flights", sa.Boolean(), nullable=True),
        sa.Column("edit_tournaments", sa.Boolean(), nullable=True),
        sa.Column("edit_payments", sa.Boolean(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "flight",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=True),
        sa.Column("logo_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("secretary", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("secretary_email", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("secretary_phone", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("signup_start_date", sa.DateTime(), nullable=False),
        sa.Column("signup_stop_date", sa.DateTime(), nullable=False),
        sa.Column("start_date", sa.DateTime(), nullable=False),
        sa.Column("weeks", sa.Integer(), nullable=False),
        sa.Column("tee_times", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("locked", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["course.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "leagueduespayment",
        sa.Column("golfer_id", sa.Integer(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("amount_due", sa.Float(), nullable=False),
        sa.Column("amount_paid", sa.Float(), nullable=True),
        sa.Column("is_paid", sa.Boolean(), nullable=True),
        sa.Column("linked_payment_id", sa.Integer(), nullable=True),
        sa.Column(
            "method",
            sa.Enum(
                "CASH_OR_CHECK",
                "PAYPAL",
                "EXEMPT",
                "LINKED",
                name="payment_method_enum",
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("comment", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["golfer_id"],
            ["golfer.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "qualifyingscore",
        sa.Column("golfer_id", sa.Integer(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "QUALIFYING_ROUND",
                "OFFICIAL_HANDICAP_INDEX",
                name="qualifying_score_type_enum",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("score_differential", sa.Float(), nullable=False),
        sa.Column("date_updated", sa.DateTime(), nullable=False),
        sa.Column("date_played", sa.DateTime(), nullable=True),
        sa.Column("course_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("track_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("tee_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("tee_gender", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("tee_par", sa.Integer(), nullable=True),
        sa.Column("tee_rating", sa.Float(), nullable=True),
        sa.Column("tee_slope", sa.Float(), nullable=True),
        sa.Column("gross_score", sa.Integer(), nullable=True),
        sa.Column("adjusted_gross_score", sa.Integer(), nullable=True),
        sa.Column("comment", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["golfer_id"],
            ["golfer.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tournament",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=True),
        sa.Column("course_id", sa.Integer(), nullable=True),
        sa.Column("logo_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("secretary", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("secretary_email", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("secretary_phone", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("signup_start_date", sa.DateTime(), nullable=True),
        sa.Column("signup_stop_date", sa.DateTime(), nullable=True),
        sa.Column("members_entry_fee", sa.Float(), nullable=True),
        sa.Column("non_members_entry_fee", sa.Float(), nullable=True),
        sa.Column("shotgun", sa.Boolean(), nullable=True),
        sa.Column("strokeplay", sa.Boolean(), nullable=True),
        sa.Column("bestball", sa.Integer(), nullable=True),
        sa.Column("scramble", sa.Boolean(), nullable=True),
        sa.Column("shamble", sa.Boolean(), nullable=True),
        sa.Column("ryder_cup", sa.Boolean(), nullable=True),
        sa.Column("individual", sa.Boolean(), nullable=True),
        sa.Column("chachacha", sa.Boolean(), nullable=True),
        sa.Column("locked", sa.Boolean(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["course.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "track",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["course.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "flightteamlink",
        sa.Column("flight_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["flight_id"],
            ["flight.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["team.id"],
        ),
        sa.PrimaryKeyConstraint("flight_id", "team_id"),
    )
    op.create_table(
        "match",
        sa.Column("flight_id", sa.Integer(), nullable=True),
        sa.Column("week", sa.Integer(), nullable=False),
        sa.Column("home_team_id", sa.Integer(), nullable=True),
        sa.Column("away_team_id", sa.Integer(), nullable=True),
        sa.Column("home_score", sa.Float(), nullable=True),
        sa.Column("away_score", sa.Float(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["away_team_id"],
            ["team.id"],
        ),
        sa.ForeignKeyConstraint(
            ["flight_id"],
            ["flight.id"],
        ),
        sa.ForeignKeyConstraint(
            ["home_team_id"],
            ["team.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tee",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "gender",
            sa.Enum("MENS", "LADIES", name="tee_gender_enum", create_constraint=True),
            nullable=False,
        ),
        sa.Column("rating", sa.Float(), nullable=False),
        sa.Column("slope", sa.Integer(), nullable=False),
        sa.Column("color", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("track_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["track.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tournamententryfeepayment",
        sa.Column("golfer_id", sa.Integer(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("tournament_id", sa.Integer(), nullable=True),
        sa.Column(
            "type",
            sa.Enum(
                "MEMBER_FEE",
                "NON_MEMBER_FEE",
                name="tournament_entry_fee_type_enum",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("amount_due", sa.Float(), nullable=False),
        sa.Column("amount_paid", sa.Float(), nullable=True),
        sa.Column("is_paid", sa.Boolean(), nullable=True),
        sa.Column("linked_payment_id", sa.Integer(), nullable=True),
        sa.Column(
            "method",
            sa.Enum(
                "CASH_OR_CHECK",
                "PAYPAL",
                "EXEMPT",
                "LINKED",
                name="payment_method_enum",
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("comment", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["golfer_id"],
            ["golfer.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tournament_id"],
            ["tournament.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tournamentteamlink",
        sa.Column("tournament_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["team.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tournament_id"],
            ["tournament.id"],
        ),
        sa.PrimaryKeyConstraint("tournament_id", "team_id"),
    )
    op.create_table(
        "division",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("gender", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("primary_tee_id", sa.Integer(), nullable=True),
        sa.Column("secondary_tee_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["primary_tee_id"],
            ["tee.id"],
        ),
        sa.ForeignKeyConstraint(
            ["secondary_tee_id"],
            ["tee.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hole",
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("par", sa.Integer(), nullable=False),
        sa.Column("yardage", sa.Integer(), nullable=True),
        sa.Column("stroke_index", sa.Integer(), nullable=False),
        sa.Column("tee_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tee_id"],
            ["tee.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "round",
        sa.Column("tee_id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "QUALIFYING",
                "FLIGHT",
                "PLAYOFF",
                "TOURNAMENT",
                name="round_type_enum",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "scoring_type",
            sa.Enum(
                "INDIVIDUAL", "GROUP", name="scoring_type_enum", create_constraint=True
            ),
            nullable=True,
        ),
        sa.Column("date_played", sa.DateTime(), nullable=False),
        sa.Column("date_updated", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tee_id"],
            ["tee.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "flightdivisionlink",
        sa.Column("flight_id", sa.Integer(), nullable=False),
        sa.Column("division_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["division_id"],
            ["division.id"],
        ),
        sa.ForeignKeyConstraint(
            ["flight_id"],
            ["flight.id"],
        ),
        sa.PrimaryKeyConstraint("flight_id", "division_id"),
    )
    op.create_table(
        "flightfreeagent",
        sa.Column("golfer_id", sa.Integer(), nullable=False),
        sa.Column("flight_id", sa.Integer(), nullable=False),
        sa.Column("division_id", sa.Integer(), nullable=False),
        sa.Column(
            "cadence",
            sa.Enum(
                "WEEKLY",
                "BIWEEKLY",
                "MONTHLY",
                "OCCASIONALLY",
                name="flight_free_agent_cadence_enum",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["division_id"],
            ["division.id"],
        ),
        sa.ForeignKeyConstraint(
            ["flight_id"],
            ["flight.id"],
        ),
        sa.ForeignKeyConstraint(
            ["golfer_id"],
            ["golfer.id"],
        ),
        sa.PrimaryKeyConstraint("golfer_id", "flight_id"),
    )
    op.create_table(
        "handicapindex",
        sa.Column("golfer_id", sa.Integer(), nullable=True),
        sa.Column("round_id", sa.Integer(), nullable=True),
        sa.Column("date_posted", sa.DateTime(), nullable=True),
        sa.Column("round_number", sa.Integer(), nullable=False),
        sa.Column("handicap_index", sa.Float(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["golfer_id"],
            ["golfer.id"],
        ),
        sa.ForeignKeyConstraint(
            ["round_id"],
            ["round.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "holeresult",
        sa.Column("round_id", sa.Integer(), nullable=False),
        sa.Column("hole_id", sa.Integer(), nullable=False),
        sa.Column("handicap_strokes", sa.Integer(), nullable=False),
        sa.Column("gross_score", sa.Integer(), nullable=False),
        sa.Column("adjusted_gross_score", sa.Integer(), nullable=False),
        sa.Column("net_score", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["hole_id"],
            ["hole.id"],
        ),
        sa.ForeignKeyConstraint(
            ["round_id"],
            ["round.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "matchroundlink",
        sa.Column("match_id", sa.Integer(), nullable=False),
        sa.Column("round_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["match.id"],
        ),
        sa.ForeignKeyConstraint(
            ["round_id"],
            ["round.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["team.id"],
        ),
        sa.PrimaryKeyConstraint("match_id", "round_id"),
    )
    op.create_table(
        "roundgolferlink",
        sa.Column("round_id", sa.Integer(), nullable=False),
        sa.Column("golfer_id", sa.Integer(), nullable=False),
        sa.Column("playing_handicap", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["golfer_id"],
            ["golfer.id"],
        ),
        sa.ForeignKeyConstraint(
            ["round_id"],
            ["round.id"],
        ),
        sa.PrimaryKeyConstraint("round_id", "golfer_id"),
    )
    op.create_table(
        "substitute",
        sa.Column("golfer_id", sa.Integer(), nullable=False),
        sa.Column("flight_id", sa.Integer(), nullable=False),
        sa.Column("division_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["division_id"],
            ["division.id"],
        ),
        sa.ForeignKeyConstraint(
            ["flight_id"],
            ["flight.id"],
        ),
        sa.ForeignKeyConstraint(
            ["golfer_id"],
            ["golfer.id"],
        ),
        sa.PrimaryKeyConstraint("golfer_id", "flight_id"),
    )
    op.create_table(
        "teamgolferlink",
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("golfer_id", sa.Integer(), nullable=False),
        sa.Column("division_id", sa.Integer(), nullable=True),
        sa.Column(
            "role",
            sa.Enum(
                "CAPTAIN",
                "PLAYER",
                "SUBSTITUTE",
                name="team_role_enum",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["division_id"],
            ["division.id"],
        ),
        sa.ForeignKeyConstraint(
            ["golfer_id"],
            ["golfer.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["team.id"],
        ),
        sa.PrimaryKeyConstraint("team_id", "golfer_id"),
    )
    op.create_table(
        "tournamentdivisionlink",
        sa.Column("tournament_id", sa.Integer(), nullable=False),
        sa.Column("division_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["division_id"],
            ["division.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tournament_id"],
            ["tournament.id"],
        ),
        sa.PrimaryKeyConstraint("tournament_id", "division_id"),
    )
    op.create_table(
        "tournamentfreeagent",
        sa.Column("golfer_id", sa.Integer(), nullable=False),
        sa.Column("tournament_id", sa.Integer(), nullable=False),
        sa.Column("division_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["division_id"],
            ["division.id"],
        ),
        sa.ForeignKeyConstraint(
            ["golfer_id"],
            ["golfer.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tournament_id"],
            ["tournament.id"],
        ),
        sa.PrimaryKeyConstraint("golfer_id", "tournament_id"),
    )
    op.create_table(
        "tournamentroundlink",
        sa.Column("tournament_id", sa.Integer(), nullable=False),
        sa.Column("round_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["round_id"],
            ["round.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tournament_id"],
            ["tournament.id"],
        ),
        sa.PrimaryKeyConstraint("tournament_id", "round_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tournamentroundlink")
    op.drop_table("tournamentfreeagent")
    op.drop_table("tournamentdivisionlink")
    op.drop_table("teamgolferlink")
    op.drop_table("substitute")
    op.drop_table("roundgolferlink")
    op.drop_table("matchroundlink")
    op.drop_table("holeresult")
    op.drop_table("handicapindex")
    op.drop_table("flightfreeagent")
    op.drop_table("flightdivisionlink")
    op.drop_table("round")
    op.drop_table("hole")
    op.drop_table("division")
    op.drop_table("tournamentteamlink")
    op.drop_table("tournamententryfeepayment")
    op.drop_table("tee")
    op.drop_table("match")
    op.drop_table("flightteamlink")
    op.drop_table("track")
    op.drop_table("tournament")
    op.drop_table("qualifyingscore")
    op.drop_table("leagueduespayment")
    op.drop_table("flight")
    op.drop_table("user")
    op.drop_table("team")
    op.drop_table("season")
    op.drop_table("officer")
    op.drop_table("leaguedues")
    op.drop_table("golfer")
    op.drop_table("course")
    # ### end Alembic commands ###
