name: Deploy API to Digital Ocean (Staging)

on:
  push:
    tags:
      - "v*.*.*.dev*"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  check-formatting:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Check formatting
        uses: pre-commit/action@v3.0.1

  run-tests:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Synchronize project
        run: uv sync --dev

      - name: Run tests
        run: uv run pytest tests

  build-staging:
    runs-on: ubuntu-latest
    needs:
      - check-formatting
      - run-tests

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract tag name
        id: get_tag
        run: echo "TAG_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@8e1d5461f02b7886d3c1a774bfbd873650445aa2
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: VERSION=${{ github.ref_name }}

  deploy-staging:
    runs-on: ubuntu-latest
    needs:
      - build-staging

    permissions:
      contents: read
      packages: read

    steps:
      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USERNAME}}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            cd ~/apl-golf-league-backend

            echo ${{ secrets.GITHUB_TOKEN }} | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}

            if grep -q "^IMAGE_TAG=" ".env.staging"; then
                sed -i.bak "s/^IMAGE_TAG=.*/IMAGE_TAG=${{ github.ref_name }}/" ".env.staging"
                echo "Updated IMAGE_TAG to ${{ github.ref_name }} in .env.staging"
            else
                echo "IMAGE_TAG not found in .env.staging. Adding it with value ${{ github.ref_name }}"
                echo "IMAGE_TAG=${{ github.ref_name }}" >> ".env.staging"
            fi

            echo Stopping API container in staging...
            docker container stop aplgolfapi-staging

            echo Deploying ${{ github.ref_name }} to staging...
            docker-compose --env-file .env.staging up -d

            echo Pruning old images...
            sleep 5 # wait to ensure new container is running
            docker container prune --force
            docker image prune --all --force
